name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"   # প্রতি 5 ঘন্টা পর restart

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          DEFAULT_CHANNEL: ${{ secrets.DEFAULT_CHANNEL }}
          GDRIVE_JSON: ${{ secrets.GDRIVE_JSON }}
        run: python bot.py
